### ISSUE TITLE
bug: segmentation fault on certain DotNet projects

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#970]
# Bug
SIGSEV segmentation fault during `move2kube transform` on a Dot Net project.

## Steps to reproduce
1. Run `move2kube transform -s src/` using the given zip file as input. (zip file is too big for Github 35MB)
https://drive.google.com/file/d/1MUogUHxJeJAWetkPmtuZGHMH-d8OuK3P/view?usp=share_link

## Actual behavior
Seg fault during transform

```console
$ move2kube transform -s src/ -c cust/
? Specify a Kubernetes style selector to select only the transformers that you want to run.
ID: move2kube.transformerselector
Hints:
- Leave empty to select everything. This is the default.

 
? Select all transformer types that you are interested in:
ID: move2kube.transformers.types
Hints:
- Services that don't support any of the transformer types you are interested in will be ignored.

 ArgoCD, Buildconfig, CNBContainerizer, CloudFoundry, ClusterSelector, ComposeAnalyser, ComposeGenerator, ContainerImagesPushScriptGenerator, ContainerImagesPushScriptGenerator-v1, DockerfileDetector, DockerfileImageBuildScript, DockerfileImageBuildScript-v1, DockerfileParser, DotNetCore-Dockerfile, EarAnalyser, EarRouter, Golang-Dockerfile, Gradle, Jar, Jboss, Knative, Kubernetes, Kubernetes-v1, KubernetesVersionChanger, Liberty, Maven, Nodejs-Dockerfile, PHP-Dockerfile, Parameterizer, Python-Dockerfile, ReadMeGenerator, Ruby-Dockerfile, Rust-Dockerfile, Tekton, Tomcat, WarAnalyser, WarRouter, WinWebApp-Dockerfile, WinWebApp-Dockerfile-v1, ZuulAnalyser
? Allow spawning containers?
ID: move2kube.spawncontainers
Hints:
- If this setting is set to false, those transformers that rely on containers will not work.

 No
INFO[0002] Configuration loading done                   
INFO[0002] Start planning                               
INFO[0002] Planning started on the base directory       
INFO[0002] [CloudFoundry] Planning                      
INFO[0002] [CloudFoundry] Done                          
INFO[0002] [ComposeAnalyser] Planning                   
INFO[0002] [ComposeAnalyser] Done                       
INFO[0002] [DockerfileDetector] Planning                
INFO[0010] [DockerfileDetector] Done                    
INFO[0010] [Base Directory] Identified 0 named services and 0 to-be-named services 
INFO[0010] Planning finished on the base directory      
INFO[0010] Planning started on its sub directories      
ERRO[0010] failed to determine if the c sharp project file at the path /Users/user/Desktop/todos/21-feb-2023-biny-bug-move2kube-dotnet/t1/src/eShop.Domain/eShop.Domain.csproj is a asp net web project. Error: "no item groups in project file to parse" 
INFO[0010] Identified 1 named services and 0 to-be-named services in . 
INFO[0010] Planning finished on its sub directories     
INFO[0010] [Directory Walk] Identified 1 named services and 0 to-be-named services 
INFO[0010] [Named Services] Identified 1 named services 
INFO[0010] Planning done                                
INFO[0010] No of services identified : 1                
INFO[0010] Starting transformation                      
? Select all services that are needed:
ID: move2kube.services.[].enable
Hints:
- The services unselected here will be ignored.

 eshop
INFO[0046] Using the transformation option 'DotNetCore-Dockerfile' for the service 'eshop'. 
INFO[0046] Iteration 1                                  
INFO[0046] Iteration 2 - 1 artifacts to process         
INFO[0046] Transformer DotNetCore-Dockerfile processing 1 artifacts 
? What type of Dockerfiles should be generated for the service 'eshop'?
ID: move2kube.services."eshop".dockerfileType
Hints:
- [no build stage] There is no build stage. Dockerfiles will only contain the run stage. The .dll files will need to be built and present in the file system already, for them to get copied into the container.
- [build stage in base image] Put the build stage in a separate Dockerfile and create a base image.
- [build stage in every image] Put the build stage in every Dockerfile to make it self contained. (Warning: This may cause one build per Dockerfile.)

 build stage in base image
? For the multi-project Dot Net Core app 'eshop', please select all the child projects that should be run as services in the cluster:
ID: move2kube.services."eshop".childProjects.[].enable
Hints:
- deselect any child project that should not be run (example: libraries)

 webapi, webmvc
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x2880e91]

goroutine 1 [running]:
github.com/konveyor/move2kube/transformer/dockerfilegenerator.parsePublishProfileFile({0xc000bf1600, 0x7d})
	/Users/user/Documents/code/remote/github.com/konveyor/move2kube/transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go:665 +0xb1
github.com/konveyor/move2kube/transformer/dockerfilegenerator.getPublishProfile({0xc000c7c020?, 0x1, 0x3?}, {0xc0006ff600, 0x1e}, {0xc00075e3c0, 0x46})
	/Users/user/Documents/code/remote/github.com/konveyor/move2kube/transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go:652 +0x3e5
github.com/konveyor/move2kube/transformer/dockerfilegenerator.(*DotNetCoreDockerfileGenerator).TransformArtifact(0xc000002dc0, {{0xc003d601d0, 0x5}, {0x364da76, 0x7}, {0xc000b556b0, {0x0, 0x0, 0x0}}, 0xc000b556e0, ...}, ...)
	/Users/user/Documents/code/remote/github.com/konveyor/move2kube/transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go:461 +0x1d30
github.com/konveyor/move2kube/transformer/dockerfilegenerator.(*DotNetCoreDockerfileGenerator).Transform(0xc000ee8ea0?, {0xc0000a88c0, 0x1, 0x312f060?}, {0xc0000a8a00, 0x1, 0x1})
	/Users/user/Documents/code/remote/github.com/konveyor/move2kube/transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go:257 +0x3a5
github.com/konveyor/move2kube/transformer.runSingleTransform({_, _, _}, {_, _, _}, {_, _}, {{{0xc0007a23e0, 0x1e}, ...}, ...}, ...)
	/Users/user/Documents/code/remote/github.com/konveyor/move2kube/transformer/transformer.go:623 +0x1ee
github.com/konveyor/move2kube/transformer.transform({0xc0000a8410?, 0x26?, 0xc000147010?}, {0xc0000a8410, 0x1, 0x1}, 0x0, {0x0, 0x0}, 0xc00147c140, ...)
	/Users/user/Documents/code/remote/github.com/konveyor/move2kube/transformer/transformer.go:574 +0xb65
github.com/konveyor/move2kube/transformer.Transform({0xc0002797a0, 0x1, 0x36f28c1?}, {0xc000bca0f0, 0x46}, {0xc000bca230, 0x4c})
	/Users/user/Documents/code/remote/github.com/konveyor/move2kube/transformer/transformer.go:511 +0x588
github.com/konveyor/move2kube/lib.Transform({0x5477488?, 0x0?}, {{{0xc0002a32e0, 0x1e}, {0x364742d, 0x4}}, {{0x36542a4, 0x9}, 0x0}, {{0xc000bca0f0, ...}, ...}}, ...)
	/Users/user/Documents/code/remote/github.com/konveyor/move2kube/lib/transformer.go:88 +0x529
github.com/konveyor/move2kube/cmd.transformHandler(_, {{0x0, 0x0, {0x36460cd, 0x1}, {0x36460cd, 0x1}, {0x5477488, 0x0, 0x0}, ...}, ...})
	/Users/user/Documents/code/remote/github.com/konveyor/move2kube/cmd/transform.go:185 +0x152e
github.com/konveyor/move2kube/cmd.GetTransformCommand.func2(0xc000c3d180?, {0x36478d9?, 0x4?, 0x4?})
	/Users/user/Documents/code/remote/github.com/konveyor/move2kube/cmd/transform.go:205 +0x58
github.com/spf13/cobra.(*Command).execute(0xc000c3d180, {0xc000bfc440, 0x4, 0x4})
	/Users/user/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc000c3c780)
	/Users/user/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/user/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
main.main()
	/Users/user/Documents/code/remote/github.com/konveyor/move2kube/main.go:43 +0x21b
```

## Expected behavior
Should not get a segmentation fault.
Should print a proper error message/proceed with a warning.

## Platform
```yaml
version: v0.3.0+unreleased
gitCommit: 70c5fb88928db6108c6696b43327eafdc6d7073f
gitTreeState: clean
goVersion: go1.19.2
platform: darwin/amd64
```

## Additional context
Found by @binypanackal

**Comment by HarikrishnanBalagopal** [comment]
```
eshop
time="2023-02-21T14:52:39+05:30" level=info msg="Using the transformation option 'DotNetCore-Dockerfile' for the service 'eshop'."
time="2023-02-21T14:52:39+05:30" level=info msg="Iteration 1"
time="2023-02-21T14:52:39+05:30" level=info msg="Iteration 2 - 1 artifacts to process"
time="2023-02-21T14:52:39+05:30" level=info msg="Transformer DotNetCore-Dockerfile processing 1 artifacts"
? What type of Dockerfiles should be generated for the service 'eshop'?
ID: move2kube.services."eshop".dockerfileType
Hints:
- [no build stage] There is no build stage. Dockerfiles will only contain the run stage. The .dll files will need to be built and present in the file system already, for them to get copied into the container.
- [build stage in base image] Put the build stage in a separate Dockerfile and create a base image.
- [build stage in every image] Put the build stage in every Dockerfile to make it self contained. (Warning: This may cause one build per Dockerfile.)
 build stage in base image
? For the multi-project Dot Net Core app 'eshop', please select all the child projects that should be run as services in the cluster:
ID: move2kube.services."eshop".childProjects.[].enable
Hints:
- deselect any child project that should not be run (example: libraries)
 webapi, webmvc
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x1bfaa11]
goroutine 1 [running]:
[github.com/konveyor/move2kube/transformer/dockerfilegenerator.parsePublishProfileFile({0xc0007c5860](http://github.com/konveyor/move2kube/transformer/dockerfilegenerator.parsePublishProfileFile(%7B0xc0007c5860), 0x5c})
        /home/runner/work/move2kube/move2kube/transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go:665 +0xb1
[github.com/konveyor/move2kube/transformer/dockerfilegenerator.getPublishProfile({0xc000628470](http://github.com/konveyor/move2kube/transformer/dockerfilegenerator.getPublishProfile(%7B0xc000628470)?, 0x1, 0x3?}, {0xc0009d3fa0, 0x1e}, {0xc000d8a570, 0x25})
        /home/runner/work/move2kube/move2kube/transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go:652 +0x3e5
[github.com/konveyor/move2kube/transformer/dockerfilegenerator.(*DotNetCoreDockerfileGenerator).TransformArtifact(0xc000cc1b80](http://github.com/konveyor/move2kube/transformer/dockerfilegenerator.(*DotNetCoreDockerfileGenerator).TransformArtifact(0xc000cc1b80), {{0xc000d7e6e8, 0x5}, {0x29ba081, 0x7}, {0xc000d30b10, {0x0, 0x0, 0x0}}, 0xc000d30b40, ...}, ...)
        /home/runner/work/move2kube/move2kube/transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go:461 +0x2450
[github.com/konveyor/move2kube/transformer/dockerfilegenerator.(*DotNetCoreDockerfileGenerator).Transform(0xc000a278c0](http://github.com/konveyor/move2kube/transformer/dockerfilegenerator.(*DotNetCoreDockerfileGenerator).Transform(0xc000a278c0)?, {0xc0009c4d20, 0x1, 0x0?}, {0xc0009c5310, 0x1, 0x1})
        /home/runner/work/move2kube/move2kube/transformer/dockerfilegenerator/dotnetcoredockerfilegenerator.go:257 +0x3a5
[github.com/konveyor/move2kube/transformer.runSingleTransform({_](http://github.com/konveyor/move2kube/transformer.runSingleTransform(%7B_), _, _}, {_, _, _}, {_, _}, {{{0xc000e85920, 0x1e}, ...}, ...}, ...)
        /home/runner/work/move2kube/move2kube/transformer/transformer.go:636 +0x1ee
[github.com/konveyor/move2kube/transformer.transform({0xc0009c45f0](http://github.com/konveyor/move2kube/transformer.transform(%7B0xc0009c45f0)?, 0x26?, 0xc001007058?}, {0xc0009c45f0, 0x1, 0x1}, 0x0, {0x0, 0x0}, 0xc000f13e00, ...)
        /home/runner/work/move2kube/move2kube/transformer/transformer.go:587 +0xb65
[github.com/konveyor/move2kube/transformer.Transform({0xc000178d20](http://github.com/konveyor/move2kube/transformer.Transform(%7B0xc000178d20), 0x1, 0x2a61096?}, {0xc0001420f0, 0x21}, {0xc00004e3a8, 0x16})
        /home/runner/work/move2kube/move2kube/transformer/transformer.go:524 +0x585
[github.com/konveyor/move2kube/lib.Transform({0x47f5850](http://github.com/konveyor/move2kube/lib.Transform(%7B0x47f5850)?, 0x0?}, {{{0xc00004b320, 0x1e}, {0x29b3a1c, 0x4}}, {{0x29c08e5, 0x9}, 0x0}, {{0xc0001420f0, ...}, ...}}, ...)
        /home/runner/work/move2kube/move2kube/lib/transformer.go:87 +0x4db
[github.com/konveyor/move2kube/cmd.transformHandler(_](http://github.com/konveyor/move2kube/cmd.transformHandler(_), {{0x0, 0x0, {0x29b25af, 0x1}, {0x29b25af, 0x1}, {0x47f5850, 0x0, 0x0}, ...}, ...})
        /home/runner/work/move2kube/move2kube/cmd/transform.go:187 +0x157c
[github.com/konveyor/move2kube/cmd.GetTransformCommand.func2(0xc0000abb80](http://github.com/konveyor/move2kube/cmd.GetTransformCommand.func2(0xc0000abb80)?, {0x29b3ec0?, 0x2?, 0x2?})
        /home/runner/work/move2kube/move2kube/cmd/transform.go:207 +0x58
[github.com/spf13/cobra.(*Command).execute(0xc0000abb80](http://github.com/spf13/cobra.(*Command).execute(0xc0000abb80), {0xc000cbf1a0, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x663
[github.com/spf13/cobra.(*Command).ExecuteC(0xc0000aaf00)](http://github.com/spf13/cobra.(*Command).ExecuteC(0xc0000aaf00))
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3b4
[github.com/spf13/cobra.(*Command).Execute(...)](http://github.com/spf13/cobra.(*Command).Execute(...))
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
main.main()
        /home/runne
```
